import './globals.css'
import { Saira } from 'next/font/google'
import GraphQlProvider from '@/contexts/apolloProvider'
import { Header } from '@/components'
const saira = Saira({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <GraphQlProvider>
        <body
          className={`${saira.className} text-dark`}
          suppressHydrationWarning={true}
        >
          <Header />

          <main className="py-8 container mx-auto px-4">{children}</main>
        </body>
      </GraphQlProvider>
    </html>
  )
}
